add bug

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -53,7 +53,8 @@ jobs:
             echo "Quality Gate failed! Here are the failing conditions:"
             echo "Fetching detailed Quality Gate conditions..."
             result=$(curl -s -u $SONAR_TOKEN: "http://35.92.216.5:9000/api/qualitygates/project_status?projectKey=test-sast-python")
-            echo "$result" 
+            echo "$result"  | jq -r '.projectStatus.conditions[] | select(.status=="ERROR") | "- Metric: \(.metricKey), Value: \(.actualValue), Threshold: \(.comparator) \(.errorThreshold)"'
+            exit 1
           fi
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
